
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]
    http_cache:
         invalidation:
            enabled: true

         public: true
    defaults:
          cache_headers:
                max_age: 0
                shared_max_age: 3600
                vary: ['Content-Type','Autorization','Origin']

