<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211003205443 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE lien_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE lien_registre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE statut_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE statut_registre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE lien_plan (id INT NOT NULL, association_lot_modifier_id INT DEFAULT NULL, association_exception_modifier_id INT DEFAULT NULL, statut_plan_id INT NOT NULL, motif_modification TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3ED70C9D462B31D1 ON lien_plan (association_lot_modifier_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3ED70C9D1DCC1034 ON lien_plan (association_exception_modifier_id)');
        $this->addSql('CREATE INDEX IDX_3ED70C9D842818D7 ON lien_plan (statut_plan_id)');
        $this->addSql('CREATE TABLE lien_registre (id INT NOT NULL, association_ressource_modifier_id INT DEFAULT NULL, association_credit_modifier_id INT DEFAULT NULL, association_allocation_modifier_id INT DEFAULT NULL, statut_registre_id INT DEFAULT NULL, relation_id INT DEFAULT NULL, description_motif TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10B6D8C72D4DE99 ON lien_registre (association_ressource_modifier_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10B6D8C1DA245B3 ON lien_registre (association_credit_modifier_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10B6D8CF44461D3 ON lien_registre (association_allocation_modifier_id)');
        $this->addSql('CREATE INDEX IDX_D10B6D8C2FD19C63 ON lien_registre (statut_registre_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10B6D8C3256915B ON lien_registre (relation_id)');
        $this->addSql('CREATE TABLE statut_plan (id INT NOT NULL, plan_passation_id INT NOT NULL, statut VARCHAR(50) NOT NULL, numero INT NOT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F859C651B207B8E1 ON statut_plan (plan_passation_id)');
        $this->addSql('CREATE TABLE statut_registre (id INT NOT NULL, exercice_registre_id INT NOT NULL, statut VARCHAR(50) NOT NULL, date_debut DATE DEFAULT NULL, date_cloture DATE DEFAULT NULL, description TEXT DEFAULT NULL, est_cloturer BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A6AFFDE47D38C322 ON statut_registre (exercice_registre_id)');
        $this->addSql('ALTER TABLE lien_plan ADD CONSTRAINT FK_3ED70C9D462B31D1 FOREIGN KEY (association_lot_modifier_id) REFERENCES lot_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_plan ADD CONSTRAINT FK_3ED70C9D1DCC1034 FOREIGN KEY (association_exception_modifier_id) REFERENCES exception_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_plan ADD CONSTRAINT FK_3ED70C9D842818D7 FOREIGN KEY (statut_plan_id) REFERENCES statut_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_registre ADD CONSTRAINT FK_D10B6D8C72D4DE99 FOREIGN KEY (association_ressource_modifier_id) REFERENCES ressource_financiere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_registre ADD CONSTRAINT FK_D10B6D8C1DA245B3 FOREIGN KEY (association_credit_modifier_id) REFERENCES credit_ouvert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_registre ADD CONSTRAINT FK_D10B6D8CF44461D3 FOREIGN KEY (association_allocation_modifier_id) REFERENCES allocation_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_registre ADD CONSTRAINT FK_D10B6D8C2FD19C63 FOREIGN KEY (statut_registre_id) REFERENCES statut_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_registre ADD CONSTRAINT FK_D10B6D8C3256915B FOREIGN KEY (relation_id) REFERENCES autorisation_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_plan ADD CONSTRAINT FK_F859C651B207B8E1 FOREIGN KEY (plan_passation_id) REFERENCES plan_passation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_registre ADD CONSTRAINT FK_A6AFFDE47D38C322 FOREIGN KEY (exercice_registre_id) REFERENCES exercice_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocation_credit ADD association_allocation_actuel_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation_credit ADD mairie_communale_id INT NOT NULL');
        $this->addSql('ALTER TABLE allocation_credit ADD autorisation_marche_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation_credit ADD compte_nature_id INT NOT NULL');
        $this->addSql('ALTER TABLE allocation_credit ADD est_valide BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A4ED92F166 FOREIGN KEY (association_allocation_actuel_id) REFERENCES lien_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A4F6156921 FOREIGN KEY (mairie_communale_id) REFERENCES mairie_communale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A43018B27A FOREIGN KEY (autorisation_marche_id) REFERENCES autorisation_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A4F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23AFD6A4ED92F166 ON allocation_credit (association_allocation_actuel_id)');
        $this->addSql('CREATE INDEX IDX_23AFD6A4F6156921 ON allocation_credit (mairie_communale_id)');
        $this->addSql('CREATE INDEX IDX_23AFD6A43018B27A ON allocation_credit (autorisation_marche_id)');
        $this->addSql('CREATE INDEX IDX_23AFD6A4F8451079 ON allocation_credit (compte_nature_id)');
        $this->addSql('ALTER TABLE autorisation_marche ADD mairie_communale_id INT NOT NULL');
        $this->addSql('ALTER TABLE autorisation_marche ADD compte_nature_id INT NOT NULL');
        $this->addSql('ALTER TABLE autorisation_marche ADD relation_modifier_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE autorisation_marche ALTER objet_autorisation TYPE TEXT');
        $this->addSql('ALTER TABLE autorisation_marche ALTER objet_autorisation DROP DEFAULT');
        $this->addSql('ALTER TABLE autorisation_marche ALTER objet_autorisation TYPE TEXT');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDAF6156921 FOREIGN KEY (mairie_communale_id) REFERENCES mairie_communale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDAF8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDAB4F84D49 FOREIGN KEY (relation_modifier_id) REFERENCES lien_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_28374EDAF6156921 ON autorisation_marche (mairie_communale_id)');
        $this->addSql('CREATE INDEX IDX_28374EDAF8451079 ON autorisation_marche (compte_nature_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_28374EDAB4F84D49 ON autorisation_marche (relation_modifier_id)');
        $this->addSql('ALTER TABLE commission ADD bon_commande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE commission ADD projet_marche_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT FK_1C650158B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT FK_1C650158BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1C650158B4B54061 ON commission (bon_commande_id)');
        $this->addSql('CREATE INDEX IDX_1C650158BDB7AEC5 ON commission (projet_marche_id)');
        $this->addSql('ALTER TABLE contrat ADD association_engagement_id INT NOT NULL');
        $this->addSql('ALTER TABLE contrat ADD soumissionnaire_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrat ADD CONSTRAINT FK_6034999340BB066C FOREIGN KEY (association_engagement_id) REFERENCES engagement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contrat ADD CONSTRAINT FK_60349993D29926FB FOREIGN KEY (soumissionnaire_id) REFERENCES soumissionnaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6034999340BB066C ON contrat (association_engagement_id)');
        $this->addSql('CREATE INDEX IDX_60349993D29926FB ON contrat (soumissionnaire_id)');
        $this->addSql('ALTER TABLE credit_ouvert ADD association_credit_actuel_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE credit_ouvert ADD compte_nature_id INT NOT NULL');
        $this->addSql('ALTER TABLE credit_ouvert ADD est_valide BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE credit_ouvert ADD CONSTRAINT FK_24DCA289F72F34 FOREIGN KEY (association_credit_actuel_id) REFERENCES lien_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_ouvert ADD CONSTRAINT FK_24DCA28F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24DCA289F72F34 ON credit_ouvert (association_credit_actuel_id)');
        $this->addSql('CREATE INDEX IDX_24DCA28F8451079 ON credit_ouvert (compte_nature_id)');
        $this->addSql('ALTER TABLE decision_marche ADD contrat_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE decision_marche ADD CONSTRAINT FK_C35A77AF1823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_C35A77AF1823061F ON decision_marche (contrat_id)');
        $this->addSql('ALTER TABLE engagement ADD compte_nature_id INT NOT NULL');
        $this->addSql('ALTER TABLE engagement ADD compte_fonction_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE engagement ADD CONSTRAINT FK_D86F0141F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE engagement ADD CONSTRAINT FK_D86F01417B991374 FOREIGN KEY (compte_fonction_id) REFERENCES compte_fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_D86F0141F8451079 ON engagement (compte_nature_id)');
        $this->addSql('CREATE INDEX IDX_D86F01417B991374 ON engagement (compte_fonction_id)');
        $this->addSql('ALTER TABLE exception_marche ADD contrat_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE exception_marche ADD association_exception_actuel_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE exception_marche ADD CONSTRAINT FK_5A100FA21823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exception_marche ADD CONSTRAINT FK_5A100FA23776C8A3 FOREIGN KEY (association_exception_actuel_id) REFERENCES lien_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5A100FA21823061F ON exception_marche (contrat_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A100FA23776C8A3 ON exception_marche (association_exception_actuel_id)');
        $this->addSql('ALTER TABLE exercice_registre ADD nomenclature_id INT NOT NULL');
        $this->addSql('ALTER TABLE exercice_registre ADD ordonateur_exercice VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE exercice_registre ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE exercice_registre ADD est_en_cours BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE exercice_registre ADD CONSTRAINT FK_7133256690BFD4B8 FOREIGN KEY (nomenclature_id) REFERENCES nomenclature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_7133256690BFD4B8 ON exercice_registre (nomenclature_id)');
        $this->addSql('ALTER TABLE imputation ADD ressource_financiere_id INT NOT NULL');
        $this->addSql('ALTER TABLE imputation ADD compte_nature_id INT NOT NULL');
        $this->addSql('ALTER TABLE imputation ADD CONSTRAINT FK_AE81A25ABB7F95A1 FOREIGN KEY (ressource_financiere_id) REFERENCES ressource_financiere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE imputation ADD CONSTRAINT FK_AE81A25AF8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_AE81A25ABB7F95A1 ON imputation (ressource_financiere_id)');
        $this->addSql('CREATE INDEX IDX_AE81A25AF8451079 ON imputation (compte_nature_id)');
        $this->addSql('ALTER TABLE lot_marche ADD association_lot_actuel_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lot_marche ADD projet_marche_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lot_marche ADD est_annuler BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE lot_marche ADD CONSTRAINT FK_5D6FEFA6BB3DB540 FOREIGN KEY (association_lot_actuel_id) REFERENCES lien_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lot_marche ADD CONSTRAINT FK_5D6FEFA6BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D6FEFA6BB3DB540 ON lot_marche (association_lot_actuel_id)');
        $this->addSql('CREATE INDEX IDX_5D6FEFA6BDB7AEC5 ON lot_marche (projet_marche_id)');
        $this->addSql('ALTER TABLE mandatement ADD bon_commande_id INT NOT NULL');
        $this->addSql('ALTER TABLE mandatement ADD compte_nature_id INT NOT NULL');
        $this->addSql('ALTER TABLE mandatement ADD compte_fonction_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D448B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D448F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D4487B991374 FOREIGN KEY (compte_fonction_id) REFERENCES compte_fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_C904D448B4B54061 ON mandatement (bon_commande_id)');
        $this->addSql('CREATE INDEX IDX_C904D448F8451079 ON mandatement (compte_nature_id)');
        $this->addSql('CREATE INDEX IDX_C904D4487B991374 ON mandatement (compte_fonction_id)');
        $this->addSql('ALTER TABLE offre_marche ADD association_contrat_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE offre_marche ADD lot_marche_id INT NOT NULL');
        $this->addSql('ALTER TABLE offre_marche ADD CONSTRAINT FK_DD2BEAE738E864A5 FOREIGN KEY (association_contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offre_marche ADD CONSTRAINT FK_DD2BEAE7BF5F7755 FOREIGN KEY (lot_marche_id) REFERENCES lot_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DD2BEAE738E864A5 ON offre_marche (association_contrat_id)');
        $this->addSql('CREATE INDEX IDX_DD2BEAE7BF5F7755 ON offre_marche (lot_marche_id)');
        $this->addSql('ALTER TABLE plan_passation ADD mairie_communale_id INT NOT NULL');
        $this->addSql('ALTER TABLE plan_passation ADD exercice_registre_id INT NOT NULL');
        $this->addSql('ALTER TABLE plan_passation ADD CONSTRAINT FK_A5659D3CF6156921 FOREIGN KEY (mairie_communale_id) REFERENCES mairie_communale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_passation ADD CONSTRAINT FK_A5659D3C7D38C322 FOREIGN KEY (exercice_registre_id) REFERENCES exercice_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_A5659D3CF6156921 ON plan_passation (mairie_communale_id)');
        $this->addSql('CREATE INDEX IDX_A5659D3C7D38C322 ON plan_passation (exercice_registre_id)');
        $this->addSql('ALTER TABLE projet_marche ADD montant_projet DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE ressource_financiere ADD association_ressource_actuel_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ressource_financiere ADD statut_registre_id INT NOT NULL');
        $this->addSql('ALTER TABLE ressource_financiere ADD est_valide BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE ressource_financiere ADD CONSTRAINT FK_2AF6EA3CE9E54B0E FOREIGN KEY (association_ressource_actuel_id) REFERENCES lien_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ressource_financiere ADD CONSTRAINT FK_2AF6EA3C2FD19C63 FOREIGN KEY (statut_registre_id) REFERENCES statut_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AF6EA3CE9E54B0E ON ressource_financiere (association_ressource_actuel_id)');
        $this->addSql('CREATE INDEX IDX_2AF6EA3C2FD19C63 ON ressource_financiere (statut_registre_id)');
        $this->addSql('ALTER TABLE soumission_marche ADD projet_marche_id INT NOT NULL');
        $this->addSql('ALTER TABLE soumission_marche ADD CONSTRAINT FK_4F53C395BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_4F53C395BDB7AEC5 ON soumission_marche (projet_marche_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE exception_marche DROP CONSTRAINT FK_5A100FA23776C8A3');
        $this->addSql('ALTER TABLE lot_marche DROP CONSTRAINT FK_5D6FEFA6BB3DB540');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A4ED92F166');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDAB4F84D49');
        $this->addSql('ALTER TABLE credit_ouvert DROP CONSTRAINT FK_24DCA289F72F34');
        $this->addSql('ALTER TABLE ressource_financiere DROP CONSTRAINT FK_2AF6EA3CE9E54B0E');
        $this->addSql('ALTER TABLE lien_plan DROP CONSTRAINT FK_3ED70C9D842818D7');
        $this->addSql('ALTER TABLE lien_registre DROP CONSTRAINT FK_D10B6D8C2FD19C63');
        $this->addSql('ALTER TABLE ressource_financiere DROP CONSTRAINT FK_2AF6EA3C2FD19C63');
        $this->addSql('DROP SEQUENCE lien_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE lien_registre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE statut_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE statut_registre_id_seq CASCADE');
        $this->addSql('DROP TABLE lien_plan');
        $this->addSql('DROP TABLE lien_registre');
        $this->addSql('DROP TABLE statut_plan');
        $this->addSql('DROP TABLE statut_registre');
        $this->addSql('ALTER TABLE credit_ouvert DROP CONSTRAINT FK_24DCA28F8451079');
        $this->addSql('DROP INDEX UNIQ_24DCA289F72F34');
        $this->addSql('DROP INDEX IDX_24DCA28F8451079');
        $this->addSql('ALTER TABLE credit_ouvert DROP association_credit_actuel_id');
        $this->addSql('ALTER TABLE credit_ouvert DROP compte_nature_id');
        $this->addSql('ALTER TABLE credit_ouvert DROP est_valide');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A4F6156921');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A43018B27A');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A4F8451079');
        $this->addSql('DROP INDEX UNIQ_23AFD6A4ED92F166');
        $this->addSql('DROP INDEX IDX_23AFD6A4F6156921');
        $this->addSql('DROP INDEX IDX_23AFD6A43018B27A');
        $this->addSql('DROP INDEX IDX_23AFD6A4F8451079');
        $this->addSql('ALTER TABLE allocation_credit DROP association_allocation_actuel_id');
        $this->addSql('ALTER TABLE allocation_credit DROP mairie_communale_id');
        $this->addSql('ALTER TABLE allocation_credit DROP autorisation_marche_id');
        $this->addSql('ALTER TABLE allocation_credit DROP compte_nature_id');
        $this->addSql('ALTER TABLE allocation_credit DROP est_valide');
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_6034999340BB066C');
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_60349993D29926FB');
        $this->addSql('DROP INDEX UNIQ_6034999340BB066C');
        $this->addSql('DROP INDEX IDX_60349993D29926FB');
        $this->addSql('ALTER TABLE contrat DROP association_engagement_id');
        $this->addSql('ALTER TABLE contrat DROP soumissionnaire_id');
        $this->addSql('DROP INDEX UNIQ_2AF6EA3CE9E54B0E');
        $this->addSql('DROP INDEX IDX_2AF6EA3C2FD19C63');
        $this->addSql('ALTER TABLE ressource_financiere DROP association_ressource_actuel_id');
        $this->addSql('ALTER TABLE ressource_financiere DROP statut_registre_id');
        $this->addSql('ALTER TABLE ressource_financiere DROP est_valide');
        $this->addSql('ALTER TABLE projet_marche DROP montant_projet');
        $this->addSql('ALTER TABLE decision_marche DROP CONSTRAINT FK_C35A77AF1823061F');
        $this->addSql('DROP INDEX IDX_C35A77AF1823061F');
        $this->addSql('ALTER TABLE decision_marche DROP contrat_id');
        $this->addSql('ALTER TABLE engagement DROP CONSTRAINT FK_D86F0141F8451079');
        $this->addSql('ALTER TABLE engagement DROP CONSTRAINT FK_D86F01417B991374');
        $this->addSql('DROP INDEX IDX_D86F0141F8451079');
        $this->addSql('DROP INDEX IDX_D86F01417B991374');
        $this->addSql('ALTER TABLE engagement DROP compte_nature_id');
        $this->addSql('ALTER TABLE engagement DROP compte_fonction_id');
        $this->addSql('ALTER TABLE plan_passation DROP CONSTRAINT FK_A5659D3CF6156921');
        $this->addSql('ALTER TABLE plan_passation DROP CONSTRAINT FK_A5659D3C7D38C322');
        $this->addSql('DROP INDEX IDX_A5659D3CF6156921');
        $this->addSql('DROP INDEX IDX_A5659D3C7D38C322');
        $this->addSql('ALTER TABLE plan_passation DROP mairie_communale_id');
        $this->addSql('ALTER TABLE plan_passation DROP exercice_registre_id');
        $this->addSql('ALTER TABLE exception_marche DROP CONSTRAINT FK_5A100FA21823061F');
        $this->addSql('DROP INDEX IDX_5A100FA21823061F');
        $this->addSql('DROP INDEX UNIQ_5A100FA23776C8A3');
        $this->addSql('ALTER TABLE exception_marche DROP contrat_id');
        $this->addSql('ALTER TABLE exception_marche DROP association_exception_actuel_id');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDAF6156921');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDAF8451079');
        $this->addSql('DROP INDEX IDX_28374EDAF6156921');
        $this->addSql('DROP INDEX IDX_28374EDAF8451079');
        $this->addSql('DROP INDEX UNIQ_28374EDAB4F84D49');
        $this->addSql('ALTER TABLE autorisation_marche DROP mairie_communale_id');
        $this->addSql('ALTER TABLE autorisation_marche DROP compte_nature_id');
        $this->addSql('ALTER TABLE autorisation_marche DROP relation_modifier_id');
        $this->addSql('ALTER TABLE autorisation_marche ALTER objet_autorisation TYPE VARCHAR(1000)');
        $this->addSql('ALTER TABLE autorisation_marche ALTER objet_autorisation DROP DEFAULT');
        $this->addSql('ALTER TABLE imputation DROP CONSTRAINT FK_AE81A25ABB7F95A1');
        $this->addSql('ALTER TABLE imputation DROP CONSTRAINT FK_AE81A25AF8451079');
        $this->addSql('DROP INDEX IDX_AE81A25ABB7F95A1');
        $this->addSql('DROP INDEX IDX_AE81A25AF8451079');
        $this->addSql('ALTER TABLE imputation DROP ressource_financiere_id');
        $this->addSql('ALTER TABLE imputation DROP compte_nature_id');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D448B4B54061');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D448F8451079');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D4487B991374');
        $this->addSql('DROP INDEX IDX_C904D448B4B54061');
        $this->addSql('DROP INDEX IDX_C904D448F8451079');
        $this->addSql('DROP INDEX IDX_C904D4487B991374');
        $this->addSql('ALTER TABLE mandatement DROP bon_commande_id');
        $this->addSql('ALTER TABLE mandatement DROP compte_nature_id');
        $this->addSql('ALTER TABLE mandatement DROP compte_fonction_id');
        $this->addSql('ALTER TABLE lot_marche DROP CONSTRAINT FK_5D6FEFA6BDB7AEC5');
        $this->addSql('DROP INDEX UNIQ_5D6FEFA6BB3DB540');
        $this->addSql('DROP INDEX IDX_5D6FEFA6BDB7AEC5');
        $this->addSql('ALTER TABLE lot_marche DROP association_lot_actuel_id');
        $this->addSql('ALTER TABLE lot_marche DROP projet_marche_id');
        $this->addSql('ALTER TABLE lot_marche DROP est_annuler');
        $this->addSql('ALTER TABLE offre_marche DROP CONSTRAINT FK_DD2BEAE738E864A5');
        $this->addSql('ALTER TABLE offre_marche DROP CONSTRAINT FK_DD2BEAE7BF5F7755');
        $this->addSql('DROP INDEX UNIQ_DD2BEAE738E864A5');
        $this->addSql('DROP INDEX IDX_DD2BEAE7BF5F7755');
        $this->addSql('ALTER TABLE offre_marche DROP association_contrat_id');
        $this->addSql('ALTER TABLE offre_marche DROP lot_marche_id');
        $this->addSql('ALTER TABLE soumission_marche DROP CONSTRAINT FK_4F53C395BDB7AEC5');
        $this->addSql('DROP INDEX IDX_4F53C395BDB7AEC5');
        $this->addSql('ALTER TABLE soumission_marche DROP projet_marche_id');
        $this->addSql('ALTER TABLE commission DROP CONSTRAINT FK_1C650158B4B54061');
        $this->addSql('ALTER TABLE commission DROP CONSTRAINT FK_1C650158BDB7AEC5');
        $this->addSql('DROP INDEX IDX_1C650158B4B54061');
        $this->addSql('DROP INDEX IDX_1C650158BDB7AEC5');
        $this->addSql('ALTER TABLE commission DROP bon_commande_id');
        $this->addSql('ALTER TABLE commission DROP projet_marche_id');
        $this->addSql('ALTER TABLE exercice_registre DROP CONSTRAINT FK_7133256690BFD4B8');
        $this->addSql('DROP INDEX IDX_7133256690BFD4B8');
        $this->addSql('ALTER TABLE exercice_registre DROP nomenclature_id');
        $this->addSql('ALTER TABLE exercice_registre DROP ordonateur_exercice');
        $this->addSql('ALTER TABLE exercice_registre DROP description');
        $this->addSql('ALTER TABLE exercice_registre DROP est_en_cours');
    }
}
