<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211115160308 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE allocation_credit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE autorisation_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bailleur_fonds_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bon_commande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE compte_fonction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE compte_nature_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contrat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credit_ouvert_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE decision_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE engagement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exception_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exercice_registre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE imputation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_commande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE lien_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE lot_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mairie_communale_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mandatement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE membre_commission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mode_passation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nomenclature_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE offre_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE participant_commission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE phase_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_passation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE projet_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ressource_financiere_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE soumission_marche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE soumissionnaire_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE statut_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE statut_registre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE allocation_credit (id INT NOT NULL, credit_ouvert_id INT NOT NULL, autorisation_marche_id INT NOT NULL, actualise_allocation_id INT DEFAULT NULL, montant_allouer DOUBLE PRECISION NOT NULL, description_allocation VARCHAR(255) DEFAULT NULL, est_valide BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_23AFD6A46967D083 ON allocation_credit (credit_ouvert_id)');
        $this->addSql('CREATE INDEX IDX_23AFD6A43018B27A ON allocation_credit (autorisation_marche_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23AFD6A47B597B10 ON allocation_credit (actualise_allocation_id)');
        $this->addSql('CREATE TABLE autorisation_marche (id INT NOT NULL, mairie_communale_id INT NOT NULL, compte_nature_id INT NOT NULL, association_registre_id INT NOT NULL, association_statut_id INT NOT NULL, association_credit_id INT DEFAULT NULL, actualisation_autorisation_id INT DEFAULT NULL, objet_autorisation TEXT NOT NULL, montant_autorisation DOUBLE PRECISION NOT NULL, explication_autorisation TEXT DEFAULT NULL, est_valide BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_28374EDAF6156921 ON autorisation_marche (mairie_communale_id)');
        $this->addSql('CREATE INDEX IDX_28374EDAF8451079 ON autorisation_marche (compte_nature_id)');
        $this->addSql('CREATE INDEX IDX_28374EDA7DEC7E3A ON autorisation_marche (association_registre_id)');
        $this->addSql('CREATE INDEX IDX_28374EDA52C73171 ON autorisation_marche (association_statut_id)');
        $this->addSql('CREATE INDEX IDX_28374EDA6AE1268C ON autorisation_marche (association_credit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_28374EDA37468E17 ON autorisation_marche (actualisation_autorisation_id)');
        $this->addSql('CREATE TABLE autorisation_marche_bailleur_fonds (autorisation_marche_id INT NOT NULL, bailleur_fonds_id INT NOT NULL, PRIMARY KEY(autorisation_marche_id, bailleur_fonds_id))');
        $this->addSql('CREATE INDEX IDX_55767A983018B27A ON autorisation_marche_bailleur_fonds (autorisation_marche_id)');
        $this->addSql('CREATE INDEX IDX_55767A984A5D0223 ON autorisation_marche_bailleur_fonds (bailleur_fonds_id)');
        $this->addSql('CREATE TABLE bailleur_fonds (id INT NOT NULL, designation_bailleur VARCHAR(100) NOT NULL, sigle_bailleur VARCHAR(10) NOT NULL, categorie_bailleur VARCHAR(50) NOT NULL, code_bailleur VARCHAR(10) NOT NULL, source_financement VARCHAR(255) NOT NULL, description_bailleur VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bon_commande (id INT NOT NULL, contrat_id INT NOT NULL, numero_bon INT NOT NULL, montant_bon DOUBLE PRECISION NOT NULL, date_demarrage DATE DEFAULT NULL, delai_execution INT DEFAULT NULL, date_reception_normal DATE DEFAULT NULL, date_reception_effective DATE DEFAULT NULL, est_receptioner BOOLEAN NOT NULL, lieu_reception VARCHAR(255) DEFAULT NULL, montant_penalite DOUBLE PRECISION DEFAULT NULL, objet_penalite TEXT DEFAULT NULL, description_reception TEXT DEFAULT NULL, description_bon TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_159D95761823061F ON bon_commande (contrat_id)');
        $this->addSql('CREATE TABLE commission (id INT NOT NULL, bon_commande_id INT DEFAULT NULL, projet_marche_id INT DEFAULT NULL, type_commission VARCHAR(255) NOT NULL, reference_convocation VARCHAR(100) NOT NULL, objet_convocation VARCHAR(500) NOT NULL, date_convocation DATE NOT NULL, description_convocation TEXT DEFAULT NULL, date_notification DATE DEFAULT NULL, date_debut_session DATE DEFAULT NULL, date_fin_session DATE DEFAULT NULL, synthese_session_ouverture TEXT DEFAULT NULL, heure_debut_session TIME(0) WITHOUT TIME ZONE DEFAULT NULL, heure_fin_session_ouverture TIME(0) WITHOUT TIME ZONE DEFAULT NULL, heure_debut_session_fermeture TIME(0) WITHOUT TIME ZONE DEFAULT NULL, heure_fin_session_fermeture TIME(0) WITHOUT TIME ZONE DEFAULT NULL, synthese_fermeture TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1C650158B4B54061 ON commission (bon_commande_id)');
        $this->addSql('CREATE INDEX IDX_1C650158BDB7AEC5 ON commission (projet_marche_id)');
        $this->addSql('CREATE TABLE compte_fonction (id INT NOT NULL, nomenclature_id INT DEFAULT NULL, compte_fonction_id INT DEFAULT NULL, numero_compte_fonction INT NOT NULL, libelle_compte_fonction VARCHAR(255) NOT NULL, hierachie_compte_fonction VARCHAR(30) NOT NULL, description_compte_fonction VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8BB0464090BFD4B8 ON compte_fonction (nomenclature_id)');
        $this->addSql('CREATE INDEX IDX_8BB046407B991374 ON compte_fonction (compte_fonction_id)');
        $this->addSql('CREATE TABLE compte_nature (id INT NOT NULL, nomenclature_id INT DEFAULT NULL, compte_nature_id INT DEFAULT NULL, numero_compte_nature INT NOT NULL, libelle_compte_nature VARCHAR(255) NOT NULL, section_compte_nature VARCHAR(30) DEFAULT NULL, hierachie_compte_nature VARCHAR(30) NOT NULL, description_compte_nature VARCHAR(255) DEFAULT NULL, credit_affect BOOLEAN NOT NULL, auto_affect BOOLEAN NOT NULL, actuel_compte BOOLEAN DEFAULT NULL, actuel_auto BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B41DB9090BFD4B8 ON compte_nature (nomenclature_id)');
        $this->addSql('CREATE INDEX IDX_6B41DB90F8451079 ON compte_nature (compte_nature_id)');
        $this->addSql('CREATE TABLE contrat (id INT NOT NULL, marche_id INT DEFAULT NULL, association_engagement_id INT NOT NULL, soumissionnaire_id INT DEFAULT NULL, type_contrat VARCHAR(50) NOT NULL, montant_minimum DOUBLE PRECISION DEFAULT NULL, montant_maximum DOUBLE PRECISION DEFAULT NULL, numero_contrat INT NOT NULL, reference_contrat VARCHAR(255) NOT NULL, date_approbation DATE DEFAULT NULL, date_notification DATE DEFAULT NULL, est_approuver BOOLEAN NOT NULL, description_contrat TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_603499939E494911 ON contrat (marche_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6034999340BB066C ON contrat (association_engagement_id)');
        $this->addSql('CREATE INDEX IDX_60349993D29926FB ON contrat (soumissionnaire_id)');
        $this->addSql('CREATE TABLE credit_ouvert (id INT NOT NULL, ressource_financiere_id INT NOT NULL, compte_nature_id INT NOT NULL, actualise_credit_id INT DEFAULT NULL, montant_inscription DOUBLE PRECISION NOT NULL, description_inscription VARCHAR(255) DEFAULT NULL, est_valide BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_24DCA28BB7F95A1 ON credit_ouvert (ressource_financiere_id)');
        $this->addSql('CREATE INDEX IDX_24DCA28F8451079 ON credit_ouvert (compte_nature_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24DCA281F649EDF ON credit_ouvert (actualise_credit_id)');
        $this->addSql('CREATE TABLE decision_marche (id INT NOT NULL, projet_marche_id INT DEFAULT NULL, contrat_id INT DEFAULT NULL, objet_decision VARCHAR(500) DEFAULT NULL, numero_decision INT NOT NULL, reference_decision VARCHAR(255) DEFAULT NULL, date_decision DATE DEFAULT NULL, est_publier BOOLEAN NOT NULL, journal_publication VARCHAR(255) DEFAULT NULL, numero_publication INT DEFAULT NULL, date_publication DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C35A77AFBDB7AEC5 ON decision_marche (projet_marche_id)');
        $this->addSql('CREATE INDEX IDX_C35A77AF1823061F ON decision_marche (contrat_id)');
        $this->addSql('CREATE TABLE engagement (id INT NOT NULL, emission_id INT DEFAULT NULL, compte_nature_id INT NOT NULL, compte_fonction_id INT DEFAULT NULL, type_operation VARCHAR(50) NOT NULL, montant_operation DOUBLE PRECISION NOT NULL, date_operation DATE NOT NULL, reference_operation VARCHAR(100) DEFAULT NULL, description_operation TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D86F014117E24D70 ON engagement (emission_id)');
        $this->addSql('CREATE INDEX IDX_D86F0141F8451079 ON engagement (compte_nature_id)');
        $this->addSql('CREATE INDEX IDX_D86F01417B991374 ON engagement (compte_fonction_id)');
        $this->addSql('CREATE TABLE exception_marche (id INT NOT NULL, plan_passation_id INT NOT NULL, autorisation_marche_id INT NOT NULL, contrat_id INT DEFAULT NULL, association_exception_actuel_id INT DEFAULT NULL, type_exception VARCHAR(100) NOT NULL, objet_exception VARCHAR(500) DEFAULT NULL, montant_exception DOUBLE PRECISION NOT NULL, observation_exception VARCHAR(255) DEFAULT NULL, delai_excecution INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5A100FA2B207B8E1 ON exception_marche (plan_passation_id)');
        $this->addSql('CREATE INDEX IDX_5A100FA23018B27A ON exception_marche (autorisation_marche_id)');
        $this->addSql('CREATE INDEX IDX_5A100FA21823061F ON exception_marche (contrat_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A100FA23776C8A3 ON exception_marche (association_exception_actuel_id)');
        $this->addSql('CREATE TABLE exercice_registre (id INT NOT NULL, nomenclature_id INT NOT NULL, annee_exercice INT NOT NULL, ordonateur_exercice VARCHAR(255) NOT NULL, date_vote DATE DEFAULT NULL, date_adoption DATE DEFAULT NULL, description TEXT DEFAULT NULL, est_ouvert BOOLEAN NOT NULL, date_cloture DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7133256690BFD4B8 ON exercice_registre (nomenclature_id)');
        $this->addSql('CREATE TABLE imputation (id INT NOT NULL, engagement_id INT DEFAULT NULL, mandatement_id INT DEFAULT NULL, ressource_financiere_id INT NOT NULL, compte_nature_id INT NOT NULL, type_imputation VARCHAR(50) NOT NULL, montant_imputation DOUBLE PRECISION NOT NULL, description_imputation TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AE81A25AD30F6F97 ON imputation (engagement_id)');
        $this->addSql('CREATE INDEX IDX_AE81A25AFAF1DD83 ON imputation (mandatement_id)');
        $this->addSql('CREATE INDEX IDX_AE81A25ABB7F95A1 ON imputation (ressource_financiere_id)');
        $this->addSql('CREATE INDEX IDX_AE81A25AF8451079 ON imputation (compte_nature_id)');
        $this->addSql('CREATE TABLE item_commande (id INT NOT NULL, bon_commande_id INT NOT NULL, designation_item VARCHAR(500) NOT NULL, unite_item VARCHAR(100) DEFAULT NULL, prix_unitaire_item DOUBLE PRECISION NOT NULL, quantite_item INT NOT NULL, est_conforme BOOLEAN NOT NULL, description_item TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2E76EB6B4B54061 ON item_commande (bon_commande_id)');
        $this->addSql('CREATE TABLE lien_plan (id INT NOT NULL, association_lot_modifier_id INT DEFAULT NULL, association_exception_modifier_id INT DEFAULT NULL, statut_plan_id INT NOT NULL, motif_modification TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3ED70C9D462B31D1 ON lien_plan (association_lot_modifier_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3ED70C9D1DCC1034 ON lien_plan (association_exception_modifier_id)');
        $this->addSql('CREATE INDEX IDX_3ED70C9D842818D7 ON lien_plan (statut_plan_id)');
        $this->addSql('CREATE TABLE lot_marche (id INT NOT NULL, plan_passation_id INT NOT NULL, autorisation_marche_id INT NOT NULL, projet_marche_id INT DEFAULT NULL, numero_lot INT NOT NULL, objet_lot VARCHAR(500) NOT NULL, montant_lot DOUBLE PRECISION NOT NULL, observation_lot VARCHAR(255) DEFAULT NULL, delai_execution INT NOT NULL, est_annuler BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5D6FEFA6B207B8E1 ON lot_marche (plan_passation_id)');
        $this->addSql('CREATE INDEX IDX_5D6FEFA63018B27A ON lot_marche (autorisation_marche_id)');
        $this->addSql('CREATE INDEX IDX_5D6FEFA6BDB7AEC5 ON lot_marche (projet_marche_id)');
        $this->addSql('CREATE TABLE mairie_communale (id INT NOT NULL, designation_mairie VARCHAR(100) NOT NULL, abbreviation_mairie VARCHAR(10) NOT NULL, adresse_mairie VARCHAR(255) NOT NULL, description_mairie VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mandatement (id INT NOT NULL, engagement_id INT NOT NULL, emission_id INT DEFAULT NULL, bon_commande_id INT NOT NULL, compte_nature_id INT NOT NULL, compte_fonction_id INT DEFAULT NULL, type_operation VARCHAR(50) NOT NULL, montant_operation DOUBLE PRECISION NOT NULL, date_operation DATE NOT NULL, reference_operation VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, reglement VARCHAR(100) DEFAULT NULL, compte_creance VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C904D448D30F6F97 ON mandatement (engagement_id)');
        $this->addSql('CREATE INDEX IDX_C904D44817E24D70 ON mandatement (emission_id)');
        $this->addSql('CREATE INDEX IDX_C904D448B4B54061 ON mandatement (bon_commande_id)');
        $this->addSql('CREATE INDEX IDX_C904D448F8451079 ON mandatement (compte_nature_id)');
        $this->addSql('CREATE INDEX IDX_C904D4487B991374 ON mandatement (compte_fonction_id)');
        $this->addSql('CREATE TABLE membre_commission (id INT NOT NULL, matricule VARCHAR(100) DEFAULT NULL, nom_membre VARCHAR(255) NOT NULL, service_membre VARCHAR(255) DEFAULT NULL, fonction_service VARCHAR(100) DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mode_passation (id INT NOT NULL, designation_mode VARCHAR(100) NOT NULL, abbreviation_mode VARCHAR(10) NOT NULL, categorie_mode VARCHAR(100) NOT NULL, nature_prestation VARCHAR(100) NOT NULL, seuils_minimum DOUBLE PRECISION NOT NULL, seuils_maximum DOUBLE PRECISION NOT NULL, description_mode VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nomenclature (id INT NOT NULL, annee_application INT NOT NULL, decret_adoption VARCHAR(30) DEFAULT NULL, date_adoption DATE DEFAULT NULL, decret_application VARCHAR(30) DEFAULT NULL, date_application DATE DEFAULT NULL, description_nomenclature VARCHAR(255) DEFAULT NULL, est_actif BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE offre_marche (id INT NOT NULL, soumissionnaire_id INT NOT NULL, soumission_marche_id INT NOT NULL, association_contrat_id INT DEFAULT NULL, lot_marche_id INT NOT NULL, montant_minimum_offre DOUBLE PRECISION DEFAULT NULL, montant_minimum_corriger DOUBLE PRECISION DEFAULT NULL, montant_minimum_arreter DOUBLE PRECISION DEFAULT NULL, montant_maximum_offre DOUBLE PRECISION DEFAULT NULL, montant_maximum_corriger DOUBLE PRECISION DEFAULT NULL, montant_maximum_arreter DOUBLE PRECISION DEFAULT NULL, difference_minimum DOUBLE PRECISION DEFAULT NULL, difference_maximum DOUBLE PRECISION DEFAULT NULL, garanti_offre DOUBLE PRECISION DEFAULT NULL, adresse_garantie VARCHAR(255) DEFAULT NULL, compte_reglement VARCHAR(100) DEFAULT NULL, piece_non_fournir TEXT DEFAULT NULL, est_recevable BOOLEAN NOT NULL, est_taxer BOOLEAN NOT NULL, est_conforme BOOLEAN NOT NULL, classement_offre INT DEFAULT NULL, delai_execution INT DEFAULT NULL, delai_engagement INT DEFAULT NULL, remarque_offre TEXT DEFAULT NULL, date_transmission DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DD2BEAE7D29926FB ON offre_marche (soumissionnaire_id)');
        $this->addSql('CREATE INDEX IDX_DD2BEAE78F2C3BA7 ON offre_marche (soumission_marche_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DD2BEAE738E864A5 ON offre_marche (association_contrat_id)');
        $this->addSql('CREATE INDEX IDX_DD2BEAE7BF5F7755 ON offre_marche (lot_marche_id)');
        $this->addSql('CREATE TABLE participant_commission (id INT NOT NULL, membre_commission_id INT NOT NULL, commission_id INT NOT NULL, fonction_participant VARCHAR(100) NOT NULL, estpresent BOOLEAN NOT NULL, service_represente VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_20A5E746786F080 ON participant_commission (membre_commission_id)');
        $this->addSql('CREATE INDEX IDX_20A5E746202D1EB2 ON participant_commission (commission_id)');
        $this->addSql('CREATE TABLE phase_marche (id INT NOT NULL, projet_marche_id INT NOT NULL, type_phase VARCHAR(50) NOT NULL, debut_publicite DATE DEFAULT NULL, fin_publicite DATE DEFAULT NULL, duree_publicite INT NOT NULL, debut_remise_offre DATE DEFAULT NULL, fin_remise_offre DATE DEFAULT NULL, duree_remise_offre INT NOT NULL, date_demarrage DATE NOT NULL, temps_evaluation INT NOT NULL, date_ouverture_plis DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_476BC56BDB7AEC5 ON phase_marche (projet_marche_id)');
        $this->addSql('CREATE TABLE plan_passation (id INT NOT NULL, mairie_communale_id INT NOT NULL, exercice_registre_id INT NOT NULL, president_commission VARCHAR(100) DEFAULT NULL, ordonnateur_plan VARCHAR(100) NOT NULL, adresse_depouillement VARCHAR(255) DEFAULT NULL, description_plan VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A5659D3CF6156921 ON plan_passation (mairie_communale_id)');
        $this->addSql('CREATE INDEX IDX_A5659D3C7D38C322 ON plan_passation (exercice_registre_id)');
        $this->addSql('CREATE TABLE projet_marche (id INT NOT NULL, mode_passation_id INT NOT NULL, objet_marche TEXT DEFAULT NULL, montant_projet DOUBLE PRECISION DEFAULT NULL, numero_projet INT NOT NULL, reference_projet VARCHAR(255) NOT NULL, priorite_projet INT NOT NULL, specificite_projet VARCHAR(255) DEFAULT NULL, piece_fournir TEXT DEFAULT NULL, prix_dossier DOUBLE PRECISION DEFAULT NULL, proposition_minimum DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_98083A9AE29FB31A ON projet_marche (mode_passation_id)');
        $this->addSql('CREATE TABLE ressource_financiere (id INT NOT NULL, exercice_registre_id INT NOT NULL, bailleur_fonds_id INT NOT NULL, statut_registre_id INT NOT NULL, actualise_ressource_id INT DEFAULT NULL, objet_financement VARCHAR(100) NOT NULL, mode_financement VARCHAR(100) NOT NULL, montant_financement DOUBLE PRECISION NOT NULL, description_financement VARCHAR(255) DEFAULT NULL, est_valide BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2AF6EA3C7D38C322 ON ressource_financiere (exercice_registre_id)');
        $this->addSql('CREATE INDEX IDX_2AF6EA3C4A5D0223 ON ressource_financiere (bailleur_fonds_id)');
        $this->addSql('CREATE INDEX IDX_2AF6EA3C2FD19C63 ON ressource_financiere (statut_registre_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AF6EA3C9ECE7024 ON ressource_financiere (actualise_ressource_id)');
        $this->addSql('CREATE TABLE soumission_marche (id INT NOT NULL, soumissionnaire_id INT NOT NULL, projet_marche_id INT NOT NULL, numero_retrait INT NOT NULL, numero_quittance VARCHAR(100) NOT NULL, nom_represantant_retrait VARCHAR(100) DEFAULT NULL, nom_represantant_depot VARCHAR(100) DEFAULT NULL, contact_retrait VARCHAR(255) DEFAULT NULL, contact_depot VARCHAR(255) DEFAULT NULL, date_retrait DATE DEFAULT NULL, date_depot DATE DEFAULT NULL, date_annulation DATE DEFAULT NULL, numero_depot INT DEFAULT NULL, heure_depot TIME(0) WITHOUT TIME ZONE DEFAULT NULL, est_recevable BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F53C395D29926FB ON soumission_marche (soumissionnaire_id)');
        $this->addSql('CREATE INDEX IDX_4F53C395BDB7AEC5 ON soumission_marche (projet_marche_id)');
        $this->addSql('CREATE TABLE soumissionnaire (id INT NOT NULL, numero_ifu VARCHAR(100) NOT NULL, designation_entreprise VARCHAR(255) NOT NULL, sigle_entreprise VARCHAR(10) DEFAULT NULL, adresse_entreprise VARCHAR(255) NOT NULL, description_entreprise VARCHAR(500) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE statut_plan (id INT NOT NULL, plan_passation_id INT NOT NULL, statut VARCHAR(50) NOT NULL, numero INT NOT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F859C651B207B8E1 ON statut_plan (plan_passation_id)');
        $this->addSql('CREATE TABLE statut_registre (id INT NOT NULL, exercice_registre_id INT NOT NULL, statut_clos_id INT DEFAULT NULL, statut VARCHAR(50) NOT NULL, est_en_cours BOOLEAN NOT NULL, date_approbation DATE DEFAULT NULL, est_actualisable BOOLEAN NOT NULL, description_statut TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A6AFFDE47D38C322 ON statut_registre (exercice_registre_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6AFFDE4CF5DAFA7 ON statut_registre (statut_clos_id)');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A46967D083 FOREIGN KEY (credit_ouvert_id) REFERENCES credit_ouvert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A43018B27A FOREIGN KEY (autorisation_marche_id) REFERENCES autorisation_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocation_credit ADD CONSTRAINT FK_23AFD6A47B597B10 FOREIGN KEY (actualise_allocation_id) REFERENCES allocation_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDAF6156921 FOREIGN KEY (mairie_communale_id) REFERENCES mairie_communale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDAF8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDA7DEC7E3A FOREIGN KEY (association_registre_id) REFERENCES exercice_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDA52C73171 FOREIGN KEY (association_statut_id) REFERENCES statut_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDA6AE1268C FOREIGN KEY (association_credit_id) REFERENCES credit_ouvert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche ADD CONSTRAINT FK_28374EDA37468E17 FOREIGN KEY (actualisation_autorisation_id) REFERENCES autorisation_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche_bailleur_fonds ADD CONSTRAINT FK_55767A983018B27A FOREIGN KEY (autorisation_marche_id) REFERENCES autorisation_marche (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE autorisation_marche_bailleur_fonds ADD CONSTRAINT FK_55767A984A5D0223 FOREIGN KEY (bailleur_fonds_id) REFERENCES bailleur_fonds (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bon_commande ADD CONSTRAINT FK_159D95761823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT FK_1C650158B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT FK_1C650158BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE compte_fonction ADD CONSTRAINT FK_8BB0464090BFD4B8 FOREIGN KEY (nomenclature_id) REFERENCES nomenclature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE compte_fonction ADD CONSTRAINT FK_8BB046407B991374 FOREIGN KEY (compte_fonction_id) REFERENCES compte_fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE compte_nature ADD CONSTRAINT FK_6B41DB9090BFD4B8 FOREIGN KEY (nomenclature_id) REFERENCES nomenclature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE compte_nature ADD CONSTRAINT FK_6B41DB90F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contrat ADD CONSTRAINT FK_603499939E494911 FOREIGN KEY (marche_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contrat ADD CONSTRAINT FK_6034999340BB066C FOREIGN KEY (association_engagement_id) REFERENCES engagement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contrat ADD CONSTRAINT FK_60349993D29926FB FOREIGN KEY (soumissionnaire_id) REFERENCES soumissionnaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_ouvert ADD CONSTRAINT FK_24DCA28BB7F95A1 FOREIGN KEY (ressource_financiere_id) REFERENCES ressource_financiere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_ouvert ADD CONSTRAINT FK_24DCA28F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_ouvert ADD CONSTRAINT FK_24DCA281F649EDF FOREIGN KEY (actualise_credit_id) REFERENCES credit_ouvert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE decision_marche ADD CONSTRAINT FK_C35A77AFBDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE decision_marche ADD CONSTRAINT FK_C35A77AF1823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE engagement ADD CONSTRAINT FK_D86F014117E24D70 FOREIGN KEY (emission_id) REFERENCES engagement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE engagement ADD CONSTRAINT FK_D86F0141F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE engagement ADD CONSTRAINT FK_D86F01417B991374 FOREIGN KEY (compte_fonction_id) REFERENCES compte_fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exception_marche ADD CONSTRAINT FK_5A100FA2B207B8E1 FOREIGN KEY (plan_passation_id) REFERENCES plan_passation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exception_marche ADD CONSTRAINT FK_5A100FA23018B27A FOREIGN KEY (autorisation_marche_id) REFERENCES autorisation_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exception_marche ADD CONSTRAINT FK_5A100FA21823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exception_marche ADD CONSTRAINT FK_5A100FA23776C8A3 FOREIGN KEY (association_exception_actuel_id) REFERENCES lien_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exercice_registre ADD CONSTRAINT FK_7133256690BFD4B8 FOREIGN KEY (nomenclature_id) REFERENCES nomenclature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE imputation ADD CONSTRAINT FK_AE81A25AD30F6F97 FOREIGN KEY (engagement_id) REFERENCES engagement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE imputation ADD CONSTRAINT FK_AE81A25AFAF1DD83 FOREIGN KEY (mandatement_id) REFERENCES mandatement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE imputation ADD CONSTRAINT FK_AE81A25ABB7F95A1 FOREIGN KEY (ressource_financiere_id) REFERENCES ressource_financiere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE imputation ADD CONSTRAINT FK_AE81A25AF8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_commande ADD CONSTRAINT FK_2E76EB6B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_plan ADD CONSTRAINT FK_3ED70C9D462B31D1 FOREIGN KEY (association_lot_modifier_id) REFERENCES lot_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_plan ADD CONSTRAINT FK_3ED70C9D1DCC1034 FOREIGN KEY (association_exception_modifier_id) REFERENCES exception_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lien_plan ADD CONSTRAINT FK_3ED70C9D842818D7 FOREIGN KEY (statut_plan_id) REFERENCES statut_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lot_marche ADD CONSTRAINT FK_5D6FEFA6B207B8E1 FOREIGN KEY (plan_passation_id) REFERENCES plan_passation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lot_marche ADD CONSTRAINT FK_5D6FEFA63018B27A FOREIGN KEY (autorisation_marche_id) REFERENCES autorisation_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lot_marche ADD CONSTRAINT FK_5D6FEFA6BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D448D30F6F97 FOREIGN KEY (engagement_id) REFERENCES engagement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D44817E24D70 FOREIGN KEY (emission_id) REFERENCES mandatement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D448B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D448F8451079 FOREIGN KEY (compte_nature_id) REFERENCES compte_nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandatement ADD CONSTRAINT FK_C904D4487B991374 FOREIGN KEY (compte_fonction_id) REFERENCES compte_fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offre_marche ADD CONSTRAINT FK_DD2BEAE7D29926FB FOREIGN KEY (soumissionnaire_id) REFERENCES soumissionnaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offre_marche ADD CONSTRAINT FK_DD2BEAE78F2C3BA7 FOREIGN KEY (soumission_marche_id) REFERENCES soumission_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offre_marche ADD CONSTRAINT FK_DD2BEAE738E864A5 FOREIGN KEY (association_contrat_id) REFERENCES contrat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offre_marche ADD CONSTRAINT FK_DD2BEAE7BF5F7755 FOREIGN KEY (lot_marche_id) REFERENCES lot_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participant_commission ADD CONSTRAINT FK_20A5E746786F080 FOREIGN KEY (membre_commission_id) REFERENCES membre_commission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participant_commission ADD CONSTRAINT FK_20A5E746202D1EB2 FOREIGN KEY (commission_id) REFERENCES commission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE phase_marche ADD CONSTRAINT FK_476BC56BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_passation ADD CONSTRAINT FK_A5659D3CF6156921 FOREIGN KEY (mairie_communale_id) REFERENCES mairie_communale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_passation ADD CONSTRAINT FK_A5659D3C7D38C322 FOREIGN KEY (exercice_registre_id) REFERENCES exercice_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projet_marche ADD CONSTRAINT FK_98083A9AE29FB31A FOREIGN KEY (mode_passation_id) REFERENCES mode_passation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ressource_financiere ADD CONSTRAINT FK_2AF6EA3C7D38C322 FOREIGN KEY (exercice_registre_id) REFERENCES exercice_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ressource_financiere ADD CONSTRAINT FK_2AF6EA3C4A5D0223 FOREIGN KEY (bailleur_fonds_id) REFERENCES bailleur_fonds (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ressource_financiere ADD CONSTRAINT FK_2AF6EA3C2FD19C63 FOREIGN KEY (statut_registre_id) REFERENCES statut_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ressource_financiere ADD CONSTRAINT FK_2AF6EA3C9ECE7024 FOREIGN KEY (actualise_ressource_id) REFERENCES ressource_financiere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE soumission_marche ADD CONSTRAINT FK_4F53C395D29926FB FOREIGN KEY (soumissionnaire_id) REFERENCES soumissionnaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE soumission_marche ADD CONSTRAINT FK_4F53C395BDB7AEC5 FOREIGN KEY (projet_marche_id) REFERENCES projet_marche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_plan ADD CONSTRAINT FK_F859C651B207B8E1 FOREIGN KEY (plan_passation_id) REFERENCES plan_passation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_registre ADD CONSTRAINT FK_A6AFFDE47D38C322 FOREIGN KEY (exercice_registre_id) REFERENCES exercice_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_registre ADD CONSTRAINT FK_A6AFFDE4CF5DAFA7 FOREIGN KEY (statut_clos_id) REFERENCES statut_registre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A47B597B10');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A43018B27A');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDA37468E17');
        $this->addSql('ALTER TABLE autorisation_marche_bailleur_fonds DROP CONSTRAINT FK_55767A983018B27A');
        $this->addSql('ALTER TABLE exception_marche DROP CONSTRAINT FK_5A100FA23018B27A');
        $this->addSql('ALTER TABLE lot_marche DROP CONSTRAINT FK_5D6FEFA63018B27A');
        $this->addSql('ALTER TABLE autorisation_marche_bailleur_fonds DROP CONSTRAINT FK_55767A984A5D0223');
        $this->addSql('ALTER TABLE ressource_financiere DROP CONSTRAINT FK_2AF6EA3C4A5D0223');
        $this->addSql('ALTER TABLE commission DROP CONSTRAINT FK_1C650158B4B54061');
        $this->addSql('ALTER TABLE item_commande DROP CONSTRAINT FK_2E76EB6B4B54061');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D448B4B54061');
        $this->addSql('ALTER TABLE participant_commission DROP CONSTRAINT FK_20A5E746202D1EB2');
        $this->addSql('ALTER TABLE compte_fonction DROP CONSTRAINT FK_8BB046407B991374');
        $this->addSql('ALTER TABLE engagement DROP CONSTRAINT FK_D86F01417B991374');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D4487B991374');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDAF8451079');
        $this->addSql('ALTER TABLE compte_nature DROP CONSTRAINT FK_6B41DB90F8451079');
        $this->addSql('ALTER TABLE credit_ouvert DROP CONSTRAINT FK_24DCA28F8451079');
        $this->addSql('ALTER TABLE engagement DROP CONSTRAINT FK_D86F0141F8451079');
        $this->addSql('ALTER TABLE imputation DROP CONSTRAINT FK_AE81A25AF8451079');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D448F8451079');
        $this->addSql('ALTER TABLE bon_commande DROP CONSTRAINT FK_159D95761823061F');
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_603499939E494911');
        $this->addSql('ALTER TABLE decision_marche DROP CONSTRAINT FK_C35A77AF1823061F');
        $this->addSql('ALTER TABLE exception_marche DROP CONSTRAINT FK_5A100FA21823061F');
        $this->addSql('ALTER TABLE offre_marche DROP CONSTRAINT FK_DD2BEAE738E864A5');
        $this->addSql('ALTER TABLE allocation_credit DROP CONSTRAINT FK_23AFD6A46967D083');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDA6AE1268C');
        $this->addSql('ALTER TABLE credit_ouvert DROP CONSTRAINT FK_24DCA281F649EDF');
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_6034999340BB066C');
        $this->addSql('ALTER TABLE engagement DROP CONSTRAINT FK_D86F014117E24D70');
        $this->addSql('ALTER TABLE imputation DROP CONSTRAINT FK_AE81A25AD30F6F97');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D448D30F6F97');
        $this->addSql('ALTER TABLE lien_plan DROP CONSTRAINT FK_3ED70C9D1DCC1034');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDA7DEC7E3A');
        $this->addSql('ALTER TABLE plan_passation DROP CONSTRAINT FK_A5659D3C7D38C322');
        $this->addSql('ALTER TABLE ressource_financiere DROP CONSTRAINT FK_2AF6EA3C7D38C322');
        $this->addSql('ALTER TABLE statut_registre DROP CONSTRAINT FK_A6AFFDE47D38C322');
        $this->addSql('ALTER TABLE exception_marche DROP CONSTRAINT FK_5A100FA23776C8A3');
        $this->addSql('ALTER TABLE lien_plan DROP CONSTRAINT FK_3ED70C9D462B31D1');
        $this->addSql('ALTER TABLE offre_marche DROP CONSTRAINT FK_DD2BEAE7BF5F7755');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDAF6156921');
        $this->addSql('ALTER TABLE plan_passation DROP CONSTRAINT FK_A5659D3CF6156921');
        $this->addSql('ALTER TABLE imputation DROP CONSTRAINT FK_AE81A25AFAF1DD83');
        $this->addSql('ALTER TABLE mandatement DROP CONSTRAINT FK_C904D44817E24D70');
        $this->addSql('ALTER TABLE participant_commission DROP CONSTRAINT FK_20A5E746786F080');
        $this->addSql('ALTER TABLE projet_marche DROP CONSTRAINT FK_98083A9AE29FB31A');
        $this->addSql('ALTER TABLE compte_fonction DROP CONSTRAINT FK_8BB0464090BFD4B8');
        $this->addSql('ALTER TABLE compte_nature DROP CONSTRAINT FK_6B41DB9090BFD4B8');
        $this->addSql('ALTER TABLE exercice_registre DROP CONSTRAINT FK_7133256690BFD4B8');
        $this->addSql('ALTER TABLE exception_marche DROP CONSTRAINT FK_5A100FA2B207B8E1');
        $this->addSql('ALTER TABLE lot_marche DROP CONSTRAINT FK_5D6FEFA6B207B8E1');
        $this->addSql('ALTER TABLE statut_plan DROP CONSTRAINT FK_F859C651B207B8E1');
        $this->addSql('ALTER TABLE commission DROP CONSTRAINT FK_1C650158BDB7AEC5');
        $this->addSql('ALTER TABLE decision_marche DROP CONSTRAINT FK_C35A77AFBDB7AEC5');
        $this->addSql('ALTER TABLE lot_marche DROP CONSTRAINT FK_5D6FEFA6BDB7AEC5');
        $this->addSql('ALTER TABLE phase_marche DROP CONSTRAINT FK_476BC56BDB7AEC5');
        $this->addSql('ALTER TABLE soumission_marche DROP CONSTRAINT FK_4F53C395BDB7AEC5');
        $this->addSql('ALTER TABLE credit_ouvert DROP CONSTRAINT FK_24DCA28BB7F95A1');
        $this->addSql('ALTER TABLE imputation DROP CONSTRAINT FK_AE81A25ABB7F95A1');
        $this->addSql('ALTER TABLE ressource_financiere DROP CONSTRAINT FK_2AF6EA3C9ECE7024');
        $this->addSql('ALTER TABLE offre_marche DROP CONSTRAINT FK_DD2BEAE78F2C3BA7');
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_60349993D29926FB');
        $this->addSql('ALTER TABLE offre_marche DROP CONSTRAINT FK_DD2BEAE7D29926FB');
        $this->addSql('ALTER TABLE soumission_marche DROP CONSTRAINT FK_4F53C395D29926FB');
        $this->addSql('ALTER TABLE lien_plan DROP CONSTRAINT FK_3ED70C9D842818D7');
        $this->addSql('ALTER TABLE autorisation_marche DROP CONSTRAINT FK_28374EDA52C73171');
        $this->addSql('ALTER TABLE ressource_financiere DROP CONSTRAINT FK_2AF6EA3C2FD19C63');
        $this->addSql('ALTER TABLE statut_registre DROP CONSTRAINT FK_A6AFFDE4CF5DAFA7');
        $this->addSql('DROP SEQUENCE allocation_credit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE autorisation_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bailleur_fonds_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bon_commande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE compte_fonction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE compte_nature_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contrat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credit_ouvert_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE decision_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE engagement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exception_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exercice_registre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE imputation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_commande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE lien_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE lot_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mairie_communale_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mandatement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE membre_commission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mode_passation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nomenclature_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE offre_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE participant_commission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE phase_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_passation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE projet_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ressource_financiere_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE soumission_marche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE soumissionnaire_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE statut_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE statut_registre_id_seq CASCADE');
        $this->addSql('DROP TABLE allocation_credit');
        $this->addSql('DROP TABLE autorisation_marche');
        $this->addSql('DROP TABLE autorisation_marche_bailleur_fonds');
        $this->addSql('DROP TABLE bailleur_fonds');
        $this->addSql('DROP TABLE bon_commande');
        $this->addSql('DROP TABLE commission');
        $this->addSql('DROP TABLE compte_fonction');
        $this->addSql('DROP TABLE compte_nature');
        $this->addSql('DROP TABLE contrat');
        $this->addSql('DROP TABLE credit_ouvert');
        $this->addSql('DROP TABLE decision_marche');
        $this->addSql('DROP TABLE engagement');
        $this->addSql('DROP TABLE exception_marche');
        $this->addSql('DROP TABLE exercice_registre');
        $this->addSql('DROP TABLE imputation');
        $this->addSql('DROP TABLE item_commande');
        $this->addSql('DROP TABLE lien_plan');
        $this->addSql('DROP TABLE lot_marche');
        $this->addSql('DROP TABLE mairie_communale');
        $this->addSql('DROP TABLE mandatement');
        $this->addSql('DROP TABLE membre_commission');
        $this->addSql('DROP TABLE mode_passation');
        $this->addSql('DROP TABLE nomenclature');
        $this->addSql('DROP TABLE offre_marche');
        $this->addSql('DROP TABLE participant_commission');
        $this->addSql('DROP TABLE phase_marche');
        $this->addSql('DROP TABLE plan_passation');
        $this->addSql('DROP TABLE projet_marche');
        $this->addSql('DROP TABLE ressource_financiere');
        $this->addSql('DROP TABLE soumission_marche');
        $this->addSql('DROP TABLE soumissionnaire');
        $this->addSql('DROP TABLE statut_plan');
        $this->addSql('DROP TABLE statut_registre');
    }
}
